const data = {
	products: [
		{
			_id: "1",
			name: "Apple iPhone 14 (128 GB) - Starlight",
			category: "phone",
			image:
				"https://m.media-amazon.com/images/I/3144jXPtX4L._AC_SR400,600_.jpg",
			price: 253435,
			brand: "Apple",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "2",
			name: "Pro Game MRF Genius Virat Kohli bat and Tennis Ball Combo for Kids/Adults Poplar Willow Cricket Bat (6)",
			category: "sports",
			image: "https://m.media-amazon.com/images/I/71FgTlIMXEL._AC_UL320_.jpg",
			price: 100,
			brand: "Adidas",
			rating: 4.0,
			numReviews: 13,
			description: "high quality product",
		},
		{
			_id: "3",
			name: "Lacoste Free Shirt",
			category: "Shirts",
			image: "https://m.media-amazon.com/images/I/71OFc-V+HmL._UX569_.jpg",
			price: 220,
			brand: "Lacoste",
			rating: 4.8,
			numReviews: 17,
			description: "high quality product",
		},
		{
			_id: "4",
			name: "Nike Slim Pant",
			category: "Pants",
			image: "https://m.media-amazon.com/images/I/61Pe6GirjiL._UY606_.jpg",
			price: 78,
			brand: "Nike",
			rating: 4.5,
			numReviews: 14,
			description: "high quality product",
		},
		{
			_id: "5",
			name: "Fit pant",
			category: "Pants",
			image: "https://m.media-amazon.com/images/I/71wL-coI9aL._AC_UL320_.jpg",
			price: 65,
			brand: "Puma",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "6",
			name: "Adidas Fit Pant",
			category: "Pants",
			image: "https://m.media-amazon.com/images/I/51l+RD4ibBL._AC_UL320_.jpg",
			price: 139,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 15,
			description: "high quality product",
		},
	],
};
export default data;
